---
# handlers file for homeworkstation

- name: start avahi
  systemd: 
    name: avahi-daemon.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: start samba
  systemd: 
    name: smbd.service
    state: started
    enabled: yes
    daemon_reload: yes

- name: start srv-media
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
    daemon_reload: yes
  with_items:
    - srv-media.mount
    - srv-media.automount

- name: restart samba
  systemd: 
    name: smbd.service
    state: restarted
