---
- name: ensure presence of base packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 21600
  with_items:
    - apt-transport-https
    - bash-completion
    - ca-certificates
    - curl
    - git
    - htop
    - software-properties-common
    - vim

- include: root.yml
- include: skel.yml
- include: timezone.yml
- include: users.yml
