---
- name: firewall - ensure ufw is active
  ufw: state=enabled policy=allow logging=on

- name: firewall - ensure default services are available
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
  with_items:
    - port: 22
      protocol: "tcp"
    - port: 80
      protocol: "tcp"
    - port: 443
      protocol: "tcp"
